export const selectedItems = [
  {
    id: 1,
    image: "images/item1.svg",
    name: "Вытяжное устройство G2H",
    description:
      "12-72/168 м3/ч / гидрорегулируемый расход /  от датчика присутствия",
    article: "G2H1065",
    price: "12 644",
    count: 1,
  },
  {
    id: 2,
    image: "images/item2.svg",
    name: "Вытяжное устройство BXC",
    description:
      "12-72/168 м3/ч / гидрорегулируемый расход /  от датчика присутствия",
    article: "G2H1065",
    price: "12 644",
    count: 2,
  },
  {
    id: 3,
    image: "images/item3.svg",
    name: "Вытяжное устройство GHN",
    description:
      "12-72/168 м3/ч / гидрорегулируемый расход /  от датчика присутствия",
    article: "G2H1065",
    price: "12 644",
    count: 1,
  },
];

export const viewedProducts = [
  {
    id: 1,
    image: "images/item2.svg",
    name: "BXC",
    description: "Вытяжное устройство для механической системы вентиляции",
    priceRub: "6 848 ₽ – 56 584 ₽",
    priceEuro: "77.60 € – 643.86 €",
  },
  {
    id: 2,
    image: "images/item1.svg",
    name: "G2H",
    description: "Многофункциональное вытяжное устройство для естественной и гибридной вентиляции",
    priceRub: "6 848 ₽ – 56 584 ₽",
    priceEuro: "77.60 € – 643.86 €",
  },
  {
    id: 3,
    image: "images/item3.svg",
    name: "GHN",
    description: "Вытяжное устройство с датчиком присутствия",
    priceRub: "6 848 ₽ – 56 584 ₽",
    priceEuro: "77.60 € – 643.86 €",
  },
  {
    id: 4,
    image: "images/item4.svg",
    name: "TDA",
    description: "Вытяжное устройство с датчиком присутствия",
    priceRub: "6 848 ₽ – 56 584 ₽",
    priceEuro: "77.60 € – 643.86 €",
  },
  {
    id: 3,
    image: "images/item3.svg",
    name: "GHN",
    description: "Вытяжное устройство с датчиком присутствия",
    priceRub: "6 848 ₽ – 56 584 ₽",
    priceEuro: "77.60 € – 643.86 €",
  },
  {
    id: 4,
    image: "images/item4.svg",
    name: "TDA",
    description: "Вытяжное устройство с датчиком присутствия",
    priceRub: "6 848 ₽ – 56 584 ₽",
    priceEuro: "77.60 € – 643.86 €",
  },
  {
    id: 1,
    image: "images/item2.svg",
    name: "BXC",
    description: "Вытяжное устройство для механической системы вентиляции",
    priceRub: "6 848 ₽ – 56 584 ₽",
    priceEuro: "77.60 € – 643.86 €",
  },
  {
    id: 2,
    image: "images/item1.svg",
    name: "G2H",
    description: "Многофункциональное вытяжное устройство для естественной и гибридной вентиляции",
    priceRub: "6 848 ₽ – 56 584 ₽",
    priceEuro: "77.60 € – 643.86 €",
  },{
    id: 1,
    image: "images/item2.svg",
    name: "BXC",
    description: "Вытяжное устройство для механической системы вентиляции",
    priceRub: "6 848 ₽ – 56 584 ₽",
    priceEuro: "77.60 € – 643.86 €",
  },
  {
    id: 2,
    image: "images/item1.svg",
    name: "G2H",
    description: "Многофункциональное вытяжное устройство для естественной и гибридной вентиляции",
    priceRub: "6 848 ₽ – 56 584 ₽",
    priceEuro: "77.60 € – 643.86 €",
  },
  {
    id: 1,
    image: "images/item2.svg",
    name: "BXC",
    description: "Вытяжное устройство для механической системы вентиляции",
    priceRub: "6 848 ₽ – 56 584 ₽",
    priceEuro: "77.60 € – 643.86 €",
  },
  {
    id: 2,
    image: "images/item1.svg",
    name: "G2H",
    description: "Многофункциональное вытяжное устройство для естественной и гибридной вентиляции",
    priceRub: "6 848 ₽ – 56 584 ₽",
    priceEuro: "77.60 € – 643.86 €",
  },
  {
    id: 1,
    image: "images/item2.svg",
    name: "BXC",
    description: "Вытяжное устройство для механической системы вентиляции",
    priceRub: "6 848 ₽ – 56 584 ₽",
    priceEuro: "77.60 € – 643.86 €",
  },
  {
    id: 2,
    image: "images/item1.svg",
    name: "G2H",
    description: "Многофункциональное вытяжное устройство для естественной и гибридной вентиляции",
    priceRub: "6 848 ₽ – 56 584 ₽",
    priceEuro: "77.60 € – 643.86 €",
  },
];
